twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig'] # thème de formulaire bootstrap par symfony

when@test:
    twig:
        strict_variables: true
