symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600 # durée du lien
    throttle_limit: 3600
    enable_garbage_collection: true
